<?php
include 'connect.php';
if(isset($_POST['submit'])){
    $aid=$_POST['aid'];
    $aname=$_POST['aname'];
    $acity=$_POST['acity'];

    $sql= "INSERT INTO `agency` (`aid`,`aname`,`acity`)
            VALUES ('$aid', '$aname', '$acity')";


    $result=mysqli_query($con ,$sql);
    if($result){
    //   echo "Data inserted successfully";
      header('location:display_agency.php');
    }
    else{
      die(mysqli_error($con));
    }
}

?>




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Passenger.css">
</head>
<body>
    <div id="main">
        <div id="nav">
            <img src="images/Logo.jpg">
            <ul>
                <li><a href="home.html">Home</a></li>
                <li><a href="Passenger.php">Booking</a></li>
                <li><a href="#">Agency</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
            <input type="text" placeholder="Looking for something specific...">
            <button>Log In</button>
        </div>
        <div id="part1"></div>
        <div id="part2">
            <div id="text"><h3><i>Find and Book <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   A great Experiance...</h3></i></div>
            <div id="image">
                <h2>Agency Details:-</h2>
                <form action="agency.php" method="post">
                    <label for="pass">Id:</label>
                    <input type="text" id="pass" name="aid" placeholder="Generated by flight-Agency" readonly>
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="aname" placeholder="Enter Agency name" required>
                    <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    
                    <label for="pass">City:</label>
                    <input type="text" id="pass" name="acity" placeholder="Agency-city" required>
                    <div id="btn">
                        <!-- <button><a href="Flight.html">Next</a></button> -->
                        <button class="bu" type="submit" name="submit">submit</button>
                    </div>
                </form>
            </div>
        </div>
</div>
</body>
</html>