<?php
include 'connect.php';
$aid = $_GET['updateid'];
$sql="select * from `agency` where aid=$aid";
$result = mysqli_query($con,$sql);
$row = mysqli_fetch_assoc($result);
$aid=$row['aid'];
$aname=$row['aname'];
$acity=$row['acity'];

if(isset($_POST['submit'])){
    $aid=$_POST['aid'];
    $aname=$_POST['aname'];
    $acity=$_POST['acity'];

    $sql="UPDATE `agency` set aid='$aid', aname='$aname', acity='$acity' WHERE aid=$aid ";

    $result=mysqli_query($con ,$sql);
    if($result){
    //   echo "updated inserted successfully";
      header('location:display_agency.php');
    }
    else{
      die(mysqli_error($con));
    }
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Agency.css">
</head>
<body>
    <div id="main">
        <div id="nav">
            <img src="images/Logo.jpg">
            <ul>
                <li><a href="home.html">Home</a></li>
                <li><a href="Passenger.html">Booking</a></li>
                <li><a href="#">Agency</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
            <input type="text" placeholder="Looking for something specific...">
            <button>Log In</button>
        </div>
        <div id="part1"></div>
        <div id="part2">
            <div id="text"><h3><i>Find and Book <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   A great Experiance...</h3></i></div>
            <div id="image">
                <h2>Agency Details:-</h2>
                <form `action="agency.php"` method="post">
                    <label for="pass">Id:</label>
                    <input type="text" id="pass" name="aid" placeholder="Generated by flight-Agency" value="<?php echo $aid;?>" readonly>
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="aname" placeholder="Enter Agency name" value=<?php echo $aname;?>>
                    <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    
                    <label for="pass">City:</label>
                    <input type="text" id="pass" name="acity" placeholder="Agency-city" value=<?php echo $acity;?>>
                    <button class="bu" type="submit" name="submit">submit</button>
                </form>
                <div id="btn">
                    <!-- <button><a href="Flight-detail.html">Next</a></button> -->
                </div>
            </div>
        </div>
    </div>
</body>
</html>


